import type { Opportunity } from "./types";

const SATURN_DEPOSIT_URL = "https://app.saturn.credit/deposit";
const SATURN_USDC_VAULT_URL =
  "https://app.morpho.org/ethereum/vault/0xAbe418cc8c06D265E4EB009C02eA4B265eCA7240/saturn-usdc";

export const opportunities: Opportunity[] = [
  // ---- Base yield (hold / stake directly with Saturn) ----
  {
    id: "hold-susdat",
    name: "Hold sUSDat",
    protocol: "Saturn",
    asset: "sUSDat",
    yieldType: "Variable",
    apy: 25.9,
    apyMin: 18.0,
    apyMax: 32.0,
    riskLevel: "Medium",
    tvl: 85_400_000,
    chain: "Ethereum",
    description:
      "Stake USDat into sUSDat to earn yield backed by Saturn's STRC holdings — Strategy's (formerly MicroStrategy) preferred equity.",
    longDescription:
      "sUSDat is Saturn's ERC-4626 yield-bearing vault token. Depositing USDat mints sUSDat, representing a share of a managed pool of exposure — primarily STRC, Strategy's perpetual preferred stock. As STRC dividends accrue, the sUSDat share price increases, so yield is realized by holding rather than by receiving separate reward payouts.",
    riskExplanation:
      "Medium risk. Yield is generated from STRC preferred-equity exposure rather than Treasuries, so returns are meaningfully higher but tied to STRC's dividend performance and the value of Strategy's underlying Bitcoin-collateralized balance sheet. Unstaking from sUSDat back to USDat is subject to a short cooldown window.",
    requirements: [
      "7-day unstake cooldown applies when converting back to USDat",
      "Any Ethereum wallet holding USDat",
      "Accrue points on staked balances during active seasons",
    ],
    howToParticipate: [
      "Hold or acquire USDat",
      "Stake USDat for sUSDat on Saturn's Deposit page",
      "sUSDat share price appreciates as STRC dividends accrue",
      "Unstake after the cooldown window to redeem USDat",
    ],
    historicalYield: [
      { month: "Feb", apy: 19.2 },
      { month: "Mar", apy: 28.4 },
      { month: "Apr", apy: 31.1 },
      { month: "May", apy: 22.6 },
      { month: "Jun", apy: 24.3 },
      { month: "Jul", apy: 25.9 },
    ],
    externalUrl: SATURN_DEPOSIT_URL,
  },
  {
    id: "hold-srusdat",
    name: "Hold srUSDat (Strata Senior)",
    protocol: "Saturn",
    asset: "srUSDat",
    yieldType: "Variable",
    apy: 7.5,
    apyMin: 6.0,
    apyMax: 9.5,
    riskLevel: "Low",
    tvl: 18_200_000,
    chain: "Ethereum",
    description:
      "The senior tranche of sUSDat via Strata — targets 65% of the STRC dividend rate with reduced yield variability.",
    longDescription:
      "Strata splits sUSDat into two liquid, composable tranches — structured credit, on-chain. srUSDat is the senior position: it is first in line to be paid and is fixed at 65% of the STRC dividend rate. Any shortfall in STRC performance is absorbed first by the junior tranche (jrUSDat) principal, which is what smooths srUSDat's yield relative to holding sUSDat directly. In a normal scenario where STRC trades near par, this targets roughly 7.5% APY.",
    riskExplanation:
      "Low risk relative to sUSDat. srUSDat is protected by the junior tranche's first-loss position, so its yield is materially less volatile. Residual risk includes Strata's tranching contracts and a scenario where STRC underperformance is severe enough to also erode the senior tranche.",
    requirements: [
      "No minimum lock-up — liquid and composable",
      "Minted by depositing sUSDat into Strata",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire sUSDat by staking USDat",
      "Deposit sUSDat into Strata to mint srUSDat and jrUSDat",
      "Hold srUSDat for the senior, lower-variance yield stream",
      "Redeem via Strata or trade srUSDat directly",
    ],
    historicalYield: [
      { month: "Feb", apy: 6.8 },
      { month: "Mar", apy: 8.1 },
      { month: "Apr", apy: 9.2 },
      { month: "May", apy: 7.4 },
      { month: "Jun", apy: 6.9 },
      { month: "Jul", apy: 7.5 },
    ],
    externalUrl: SATURN_DEPOSIT_URL,
  },
  {
    id: "hold-jrusdat",
    name: "Hold jrUSDat (Strata Junior)",
    protocol: "Saturn",
    asset: "jrUSDat",
    yieldType: "Variable",
    apy: 13.0,
    apyMin: 7.0,
    apyMax: 20.0,
    riskLevel: "High",
    tvl: 9_600_000,
    chain: "Ethereum",
    description:
      "The junior tranche of sUSDat via Strata — higher, more variable yield in exchange for taking first-loss risk.",
    longDescription:
      "jrUSDat is the junior position beneath srUSDat in Saturn's Strata tranching structure — economically similar to equity below senior debt. It absorbs any STRC dividend shortfall first, which is what allows srUSDat's yield to stay fixed at 65% of the STRC rate. In exchange, jrUSDat holders receive the residual share of the sUSDat yield stream after the senior tranche is paid, which can swing with STRC performance.",
    riskExplanation:
      "High risk. jrUSDat takes the first loss in Strata's tranche waterfall — in a weak STRC dividend period, jrUSDat's yield (and potentially principal) absorbs the shortfall before srUSDat is affected at all. This is the highest-variance base product in the Saturn ecosystem.",
    requirements: [
      "No minimum lock-up — liquid and composable",
      "Minted by depositing sUSDat into Strata",
      "Understanding of first-loss tranche risk",
    ],
    howToParticipate: [
      "Acquire sUSDat by staking USDat",
      "Deposit sUSDat into Strata to mint srUSDat and jrUSDat",
      "Hold jrUSDat for the junior, higher-variance yield stream",
      "Redeem via Strata or trade jrUSDat directly",
    ],
    historicalYield: [
      { month: "Feb", apy: 9.6 },
      { month: "Mar", apy: 15.8 },
      { month: "Apr", apy: 19.4 },
      { month: "May", apy: 10.9 },
      { month: "Jun", apy: 11.6 },
      { month: "Jul", apy: 13.0 },
    ],
    externalUrl: SATURN_DEPOSIT_URL,
  },

  // ---- Pendle PT (fixed yield via Principal Tokens) — live from Pendle, 04 Jul 2026 ----
  {
    id: "pt-usdat",
    name: "PT-USDat",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "USDat",
    yieldType: "Fixed",
    apy: 7.67,
    apyMin: 7.67,
    apyMax: 7.67,
    riskLevel: "Low",
    maturityLabel: "26 Aug 2026",
    tvl: 59_840_000,
    chain: "Ethereum",
    description:
      "Lock in a fixed rate on USDat by buying its Pendle Principal Token at a discount to face value.",
    longDescription:
      "Pendle splits USDat into a Principal Token (PT) and Yield Token (YT). Buying PT-USDat at a discount and holding to maturity redeems it 1:1 for USDat, locking in a fixed, known APY regardless of how USDat's underlying rate moves — useful for savers who want certainty over Saturn's variable rate.",
    riskExplanation:
      "Low risk. Fixed yield removes rate variability, but PT-USDat is illiquid before maturity outside Pendle's secondary market, and value is still exposed to USDat's underlying smart-contract and reserve risk.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire USDat",
      "Go to the PT-USDat market on Pendle and swap USDat for PT-USDat",
      "Hold PT-USDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for USDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 7.1 },
      { month: "Mar", apy: 7.3 },
      { month: "Apr", apy: 7.9 },
      { month: "May", apy: 8.1 },
      { month: "Jun", apy: 7.5 },
      { month: "Jul", apy: 7.67 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },
  {
    id: "pt-susdat",
    name: "PT-sUSDat",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "sUSDat",
    yieldType: "Fixed",
    apy: 12.23,
    apyMin: 12.23,
    apyMax: 12.23,
    riskLevel: "Medium",
    maturityLabel: "26 Aug 2026",
    tvl: 20_110_000,
    chain: "Ethereum",
    description:
      "Lock in a fixed rate on sUSDat's STRC-backed yield by buying its Pendle Principal Token at a discount.",
    longDescription:
      "PT-sUSDat lets holders lock in today's implied fixed rate on sUSDat instead of riding its variable STRC-driven yield. Buy PT-sUSDat at a discount to sUSDat's value and redeem 1:1 for sUSDat at maturity, regardless of how sUSDat's yield fluctuates in the meantime.",
    riskExplanation:
      "Medium risk. Locking a fixed rate removes yield variability, but the market-implied rate can be well below sUSDat's trailing APY if the market expects STRC yield to fall — and PT-sUSDat still inherits sUSDat's underlying STRC and smart-contract risk.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire sUSDat by staking USDat",
      "Go to the PT-sUSDat market on Pendle and swap sUSDat for PT-sUSDat",
      "Hold PT-sUSDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for sUSDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 13.6 },
      { month: "Mar", apy: 13.0 },
      { month: "Apr", apy: 12.6 },
      { month: "May", apy: 11.9 },
      { month: "Jun", apy: 12.4 },
      { month: "Jul", apy: 12.23 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },
  {
    id: "pt-srusdat",
    name: "PT-srUSDat",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "srUSDat",
    yieldType: "Fixed",
    apy: 11.32,
    apyMin: 11.32,
    apyMax: 11.32,
    riskLevel: "Low",
    maturityLabel: "26 Aug 2026",
    tvl: 5_120_000,
    chain: "Ethereum",
    description:
      "Lock in a fixed rate on the senior Strata tranche by buying PT-srUSDat at a discount to face value.",
    longDescription:
      "PT-srUSDat applies Pendle's fixed-rate structure on top of srUSDat, Saturn's already-lower-variance senior tranche — stacking two risk-reduction mechanisms for savers who want the most conservative fixed-income-like exposure to Saturn's STRC-linked yield. The underlying srUSDat rate feeding this market currently runs around 7.8% before Pendle's fixed-rate premium.",
    riskExplanation:
      "Low risk. Combines srUSDat's first-loss protection from jrUSDat with a fixed, locked-in rate. Residual risk is limited to Pendle's and Strata's smart contracts plus PT illiquidity before maturity.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire srUSDat via Strata",
      "Go to the PT-srUSDat market on Pendle and swap srUSDat for PT-srUSDat",
      "Hold PT-srUSDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for srUSDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 10.6 },
      { month: "Mar", apy: 10.9 },
      { month: "Apr", apy: 11.6 },
      { month: "May", apy: 11.9 },
      { month: "Jun", apy: 11.1 },
      { month: "Jul", apy: 11.32 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },
  {
    id: "pt-jrusdat",
    name: "PT-jrUSDat",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "jrUSDat",
    yieldType: "Fixed",
    apy: 30.0,
    apyMin: 30.0,
    apyMax: 30.0,
    riskLevel: "High",
    maturityLabel: "26 Aug 2026",
    tvl: 19_000_000,
    chain: "Ethereum",
    description:
      "Lock in a fixed rate on the junior Strata tranche by buying PT-jrUSDat at a discount to face value.",
    longDescription:
      "PT-jrUSDat fixes today's market-implied rate on jrUSDat, Saturn's first-loss junior tranche. Pendle currently flags this as a volatile market: jrUSDat's underlying yield has recently run negative, meaning the watermark rate sits above the current exchange rate and YT is temporarily earning nothing. The 30% fixed rate reflects PT trading at a steep discount under that condition, not a guaranteed smooth return.",
    riskExplanation:
      "High risk. A fixed rate smooths the yield outcome but does not protect principal: jrUSDat remains the first-loss layer in Strata's waterfall, and Pendle itself currently marks this market as volatile due to recent negative underlying yield — PT may redeem below its purchase-implied value if that persists.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Understanding of first-loss tranche risk",
    ],
    howToParticipate: [
      "Acquire jrUSDat via Strata",
      "Go to the PT-jrUSDat market on Pendle and swap jrUSDat for PT-jrUSDat",
      "Hold PT-jrUSDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for jrUSDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 22.8 },
      { month: "Mar", apy: 27.4 },
      { month: "Apr", apy: 34.6 },
      { month: "May", apy: 31.2 },
      { month: "Jun", apy: 26.8 },
      { month: "Jul", apy: 30.0 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },
  {
    id: "pt-usdat-bnb",
    name: "PT-USDat (BNB Chain)",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "USDat",
    yieldType: "Fixed",
    apy: 9.45,
    apyMin: 9.45,
    apyMax: 9.45,
    riskLevel: "Low",
    maturityLabel: "26 Aug 2026",
    tvl: 18_450_000,
    chain: "BNB Chain",
    description:
      "Lock in a fixed rate on USDat's BNB Chain deployment by buying its Pendle Principal Token at a discount to face value.",
    longDescription:
      "USDat is bridged to BNB Chain, where Pendle runs a separate PT-USDat market alongside its Ethereum counterpart, sharing the same 26 Aug 2026 maturity. The BNB Chain market currently implies a higher fixed rate than Ethereum's, reflecting thinner liquidity and different local supply/demand for fixed exposure.",
    riskExplanation:
      "Low risk. Fixed yield removes rate variability, but this market adds bridge risk from USDat's BNB Chain deployment on top of the usual PT illiquidity-before-maturity and smart-contract risk.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge USDat to BNB Chain",
      "Go to the PT-USDat (BNB Chain) market on Pendle and swap USDat for PT-USDat",
      "Hold PT-USDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for USDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 8.8 },
      { month: "Mar", apy: 9.0 },
      { month: "Apr", apy: 9.7 },
      { month: "May", apy: 9.9 },
      { month: "Jun", apy: 9.2 },
      { month: "Jul", apy: 9.45 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },
  {
    id: "pt-susdat-bnb",
    name: "PT-sUSDat (BNB Chain)",
    protocol: "Pendle",
    pendleType: "PT",
    asset: "sUSDat",
    yieldType: "Fixed",
    apy: 15.67,
    apyMin: 15.67,
    apyMax: 15.67,
    riskLevel: "Medium",
    maturityLabel: "26 Aug 2026",
    tvl: 4_900_000,
    chain: "BNB Chain",
    description:
      "Lock in a fixed rate on sUSDat's BNB Chain deployment by buying its Pendle Principal Token at a discount to face value.",
    longDescription:
      "sUSDat is bridged to BNB Chain, where Pendle runs a separate PT-sUSDat market alongside its Ethereum counterpart, sharing the same 26 Aug 2026 maturity. This is currently Saturn's highest fixed-rate PT market, reflecting thinner BNB Chain liquidity relative to Ethereum's PT-sUSDat market.",
    riskExplanation:
      "Medium risk. Locking a fixed rate removes yield variability, but this market adds bridge risk from sUSDat's BNB Chain deployment on top of sUSDat's underlying STRC and smart-contract risk.",
    requirements: [
      "Locked until maturity (26 Aug 2026) for the quoted fixed rate",
      "Can be sold earlier on Pendle's AMM at a market-implied rate",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge sUSDat to BNB Chain",
      "Go to the PT-sUSDat (BNB Chain) market on Pendle and swap sUSDat for PT-sUSDat",
      "Hold PT-sUSDat until the 26 Aug 2026 maturity",
      "Redeem 1:1 for sUSDat at maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 14.6 },
      { month: "Mar", apy: 15.0 },
      { month: "Apr", apy: 16.4 },
      { month: "May", apy: 16.8 },
      { month: "Jun", apy: 15.2 },
      { month: "Jul", apy: 15.67 },
    ],
    externalUrl: "https://app.pendle.finance/trade/markets",
  },

  // ---- Pendle LP (variable yield from swap fees + points) — live from Pendle, 04 Jul 2026 ----
  {
    id: "lp-usdat",
    name: "USDat",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "USDat",
    yieldType: "Variable",
    apy: 2.84,
    apyMin: 1.5,
    apyMax: 6.0,
    riskLevel: "Low",
    tvl: 59_840_000,
    chain: "Ethereum",
    description:
      "Provide liquidity to the PT/SY USDat pool on Pendle to earn swap fees plus points, on top of the underlying rate.",
    longDescription:
      "Pendle LPs sit inside the PT/SY AMM for a given market, earning swap fees generated as traders move between fixed and variable exposure, plus a share of any active points program. USDat's LP APY currently runs below its PT fixed rate — a sign the market's swap fee income is modest relative to the underlying rate right now.",
    riskExplanation:
      "Low risk relative to other Pendle LPs on Saturn, since USDat is the base low-volatility asset, but LPs are still exposed to Pendle AMM impermanent-loss dynamics if the market's implied yield moves sharply before maturity.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-USDat and PT-USDat in the pool's ratio",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire USDat and wrap it into SY-USDat on Pendle",
      "Deposit SY-USDat and PT-USDat into the Pendle USDat LP pool",
      "Earn swap fees and points as the pool is traded against",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 2.1 },
      { month: "Mar", apy: 3.4 },
      { month: "Apr", apy: 4.8 },
      { month: "May", apy: 2.6 },
      { month: "Jun", apy: 2.3 },
      { month: "Jul", apy: 2.84 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },
  {
    id: "lp-susdat",
    name: "sUSDat",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "sUSDat",
    yieldType: "Variable",
    apy: 19.09,
    apyMin: 10.0,
    apyMax: 28.0,
    riskLevel: "Medium",
    tvl: 20_110_000,
    chain: "Ethereum",
    description:
      "Provide liquidity to the PT/SY sUSDat pool on Pendle to earn swap fees plus points, on top of the underlying rate.",
    longDescription:
      "This pool pairs SY-sUSDat and PT-sUSDat inside Pendle's AMM. LPs earn swap fees generated as traders rotate between fixed-rate PT-sUSDat and variable-rate exposure, plus points, currently running well above PT-sUSDat's own fixed rate.",
    riskExplanation:
      "Medium risk. In addition to Pendle AMM impermanent-loss dynamics, LP value is exposed to sUSDat's underlying STRC performance, since sUSDat's share price is the reference rate the pool is priced against.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-sUSDat and PT-sUSDat in the pool's ratio",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire sUSDat and wrap it into SY-sUSDat on Pendle",
      "Deposit SY-sUSDat and PT-sUSDat into the Pendle sUSDat LP pool",
      "Earn swap fees and points as the pool is traded against",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 15.2 },
      { month: "Mar", apy: 23.6 },
      { month: "Apr", apy: 27.1 },
      { month: "May", apy: 17.8 },
      { month: "Jun", apy: 16.4 },
      { month: "Jul", apy: 19.09 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },
  {
    id: "lp-srusdat",
    name: "srUSDat",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "srUSDat",
    yieldType: "Variable",
    apy: 13.0,
    apyMin: 8.0,
    apyMax: 20.0,
    riskLevel: "Medium",
    tvl: 5_120_000,
    chain: "Ethereum",
    description:
      "Provide liquidity to the PT/SY srUSDat pool on Pendle to earn swap fees plus points, on top of the underlying rate.",
    longDescription:
      "Pairs SY-srUSDat and PT-srUSDat inside Pendle's AMM. Because srUSDat's yield is smoothed by the junior tranche's first-loss protection, this pool's implied-yield swings are gentler than the sUSDat or jrUSDat LPs, though LPs still earn swap fees and points on top.",
    riskExplanation:
      "Medium risk. srUSDat's reduced yield variability keeps this pool's impermanent-loss profile calmer than the sUSDat and jrUSDat LPs, though it still inherits srUSDat's and Strata's underlying risks plus standard Pendle AMM dynamics.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-srUSDat and PT-srUSDat in the pool's ratio",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire srUSDat via Strata",
      "Wrap srUSDat into SY-srUSDat on Pendle",
      "Deposit SY-srUSDat and PT-srUSDat into the Pendle srUSDat LP pool",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 11.4 },
      { month: "Mar", apy: 15.8 },
      { month: "Apr", apy: 18.6 },
      { month: "May", apy: 12.1 },
      { month: "Jun", apy: 11.0 },
      { month: "Jul", apy: 13.0 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },
  {
    id: "lp-jrusdat",
    name: "jrUSDat",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "jrUSDat",
    yieldType: "Variable",
    apy: 29.45,
    apyMin: 18.0,
    apyMax: 42.0,
    riskLevel: "High",
    tvl: 19_000_000,
    chain: "Ethereum",
    description:
      "Provide liquidity to the PT/SY jrUSDat pool on Pendle to earn swap fees plus points, on top of the underlying rate.",
    longDescription:
      "Pairs SY-jrUSDat and PT-jrUSDat inside Pendle's AMM. jrUSDat's wider yield range makes this the most volatile Pendle LP on Saturn — and currently the highest-yielding, at 29.45% LP APY, well above PT-jrUSDat's own 30% fixed rate reflects a very actively traded, high-fee market.",
    riskExplanation:
      "High risk. jrUSDat is a first-loss instrument with the widest yield range in the Saturn ecosystem, and Pendle currently flags its underlying market as volatile with recent negative underlying yield — this pool carries the most impermanent-loss and principal risk of the four Pendle LPs.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-jrUSDat and PT-jrUSDat in the pool's ratio",
      "Understanding of first-loss tranche and impermanent-loss risk",
    ],
    howToParticipate: [
      "Acquire jrUSDat via Strata",
      "Wrap jrUSDat into SY-jrUSDat on Pendle",
      "Deposit SY-jrUSDat and PT-jrUSDat into the Pendle jrUSDat LP pool",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 22.8 },
      { month: "Mar", apy: 34.4 },
      { month: "Apr", apy: 41.2 },
      { month: "May", apy: 26.6 },
      { month: "Jun", apy: 24.1 },
      { month: "Jul", apy: 29.45 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },
  {
    id: "lp-usdat-bnb",
    name: "USDat (BNB Chain)",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "USDat",
    yieldType: "Variable",
    apy: 4.09,
    apyMin: 2.0,
    apyMax: 8.0,
    riskLevel: "Low",
    tvl: 18_450_000,
    chain: "BNB Chain",
    description:
      "Provide liquidity to the PT/SY USDat pool on Pendle's BNB Chain deployment to earn swap fees plus points.",
    longDescription:
      "The BNB Chain counterpart to Pendle's Ethereum USDat LP pool, sharing the same 26 Aug 2026 maturity. Thinner BNB Chain liquidity gives this pool a higher LP APY than its Ethereum equivalent.",
    riskExplanation:
      "Low risk relative to other Pendle LPs on Saturn, since USDat is the base low-volatility asset, but adds bridge risk from USDat's BNB Chain deployment on top of standard Pendle AMM impermanent-loss dynamics.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-USDat and PT-USDat in the pool's ratio on BNB Chain",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge USDat to BNB Chain and wrap it into SY-USDat on Pendle",
      "Deposit SY-USDat and PT-USDat into the Pendle USDat (BNB Chain) LP pool",
      "Earn swap fees and points as the pool is traded against",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 3.2 },
      { month: "Mar", apy: 4.6 },
      { month: "Apr", apy: 6.8 },
      { month: "May", apy: 3.9 },
      { month: "Jun", apy: 3.4 },
      { month: "Jul", apy: 4.09 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },
  {
    id: "lp-susdat-bnb",
    name: "sUSDat (BNB Chain)",
    protocol: "Pendle",
    pendleType: "LP",
    asset: "sUSDat",
    yieldType: "Variable",
    apy: 11.01,
    apyMin: 6.0,
    apyMax: 18.0,
    riskLevel: "Medium",
    tvl: 4_900_000,
    chain: "BNB Chain",
    description:
      "Provide liquidity to the PT/SY sUSDat pool on Pendle's BNB Chain deployment to earn swap fees plus points.",
    longDescription:
      "The BNB Chain counterpart to Pendle's Ethereum sUSDat LP pool, sharing the same 26 Aug 2026 maturity. LP APY here runs below the Ethereum sUSDat pool's, though still well above this market's own PT-sUSDat fixed rate.",
    riskExplanation:
      "Medium risk. In addition to Pendle AMM impermanent-loss dynamics and sUSDat's underlying STRC performance, this pool adds bridge risk from sUSDat's BNB Chain deployment.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time before maturity",
      "Deposit SY-sUSDat and PT-sUSDat in the pool's ratio on BNB Chain",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge sUSDat to BNB Chain and wrap it into SY-sUSDat on Pendle",
      "Deposit SY-sUSDat and PT-sUSDat into the Pendle sUSDat (BNB Chain) LP pool",
      "Earn swap fees and points as the pool is traded against",
      "Withdraw liquidity anytime before the market's maturity",
    ],
    historicalYield: [
      { month: "Feb", apy: 8.6 },
      { month: "Mar", apy: 12.4 },
      { month: "Apr", apy: 15.8 },
      { month: "May", apy: 10.2 },
      { month: "Jun", apy: 9.4 },
      { month: "Jul", apy: 11.01 },
    ],
    externalUrl: "https://app.pendle.finance/trade/pools",
  },

  // ---- Curve (USDat/USDC and sUSDat/USDC LPs) ----
  {
    id: "curve-usdat",
    name: "Curve LP — USDC/USDat",
    protocol: "Curve",
    asset: "USDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 6.2,
    apyMin: 4.0,
    apyMax: 9.0,
    riskLevel: "Low",
    tvl: 22_500_000,
    chain: "Ethereum",
    description:
      "Provide USDC/USDat liquidity on Curve to earn trading fees plus liquidity incentives.",
    longDescription:
      "Deposit USDC and USDat into Curve's stable pool for this pair. As both assets are designed to trade near $1, impermanent loss risk is low relative to volatile-asset pools. Earn a share of swap fees plus any active Saturn liquidity incentives on top.",
    riskExplanation:
      "Low risk. Both pool assets are stable-value, so price divergence risk is limited mainly to a USDat de-peg scenario. Standard Curve smart-contract risk applies. Note: the live APY shown reflects base trading fees only — any additional CRV/gauge incentive APY isn't included.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time",
      "Deposit USDC and USDat in the pool's ratio",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire USDC and USDat",
      "Deposit both into the Curve USDC/USDat pool",
      "Optionally stake the LP token for boosted incentives",
      "Withdraw liquidity anytime to reclaim both assets plus fees",
    ],
    historicalYield: [
      { month: "Feb", apy: 5.1 },
      { month: "Mar", apy: 6.8 },
      { month: "Apr", apy: 8.4 },
      { month: "May", apy: 5.9 },
      { month: "Jun", apy: 5.6 },
      { month: "Jul", apy: 6.2 },
    ],
    externalUrl: "https://curve.fi/#/ethereum/pools",
  },
  {
    id: "curve-susdat",
    name: "Curve LP — USDC/sUSDat",
    protocol: "Curve",
    asset: "sUSDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 8.0,
    apyMin: 8.0,
    apyMax: 8.0,
    riskLevel: "Medium",
    tvl: 14_700_000,
    chain: "Ethereum",
    description:
      "Provide USDC/sUSDat liquidity on Curve to earn trading fees plus liquidity incentives.",
    longDescription:
      "This pool pairs USDC against sUSDat, whose share price appreciates over time as STRC dividends accrue. LPs earn swap fees generated as arbitrageurs rebalance the pool against sUSDat's rising value, on top of any active liquidity incentives.",
    riskExplanation:
      "Medium risk. sUSDat's appreciating price versus a flat USDC creates directional exposure and impermanent loss dynamics beyond a pure stable-stable pool, compounded by sUSDat's underlying STRC risk. Note: the live APY shown reflects base trading fees only — any additional CRV/gauge incentive APY isn't included.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time",
      "Deposit USDC and sUSDat in the pool's ratio",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire USDC and sUSDat",
      "Deposit both into the Curve USDC/sUSDat pool",
      "Optionally stake the LP token for boosted incentives",
      "Withdraw liquidity anytime to reclaim both assets plus fees",
    ],
    historicalYield: [
      { month: "Feb", apy: 7.2 },
      { month: "Mar", apy: 8.4 },
      { month: "Apr", apy: 9.1 },
      { month: "May", apy: 7.6 },
      { month: "Jun", apy: 7.8 },
      { month: "Jul", apy: 8.0 },
    ],
    externalUrl: "https://curve.fi/#/ethereum/pools",
  },

  // ---- PancakeSwap (LP on BNB Chain) ----
  {
    id: "pancake-usdat",
    name: "PancakeSwap LP — USDT/USDat",
    protocol: "PancakeSwap",
    asset: "USDat",
    pairAsset: "USDT",
    yieldType: "Variable",
    apy: 0,
    apyMin: 0,
    apyMax: 0,
    riskLevel: "Low",
    tvl: 5_800_000,
    chain: "BNB Chain",
    description:
      "Provide USDT/USDat liquidity on PancakeSwap to earn trading fees plus CAKE incentives.",
    longDescription:
      "Bridges USDat to BNB Chain liquidity via a USDT/USDat pool on PancakeSwap. Both assets are stable-value, so impermanent loss risk is low, and Saturn layers CAKE liquidity-mining incentives on top of base swap fees.",
    riskExplanation:
      "Low risk. Both pool assets are stable-value, limiting price-divergence risk mainly to a USDat de-peg scenario. Adds bridge risk from moving USDat to BNB Chain plus standard PancakeSwap smart-contract risk.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time",
      "Deposit USDT and USDat in the pool's ratio on BNB Chain",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge USDat to BNB Chain and acquire USDT",
      "Deposit both into the PancakeSwap USDT/USDat pool",
      "Stake the LP token in PancakeSwap's farm for CAKE incentives",
      "Withdraw liquidity anytime to reclaim both assets plus fees",
    ],
    historicalYield: [
      { month: "Feb", apy: 0.4 },
      { month: "Mar", apy: 0.6 },
      { month: "Apr", apy: 0.7 },
      { month: "May", apy: 0.5 },
      { month: "Jun", apy: 0.4 },
      { month: "Jul", apy: 0.5 },
    ],
    externalUrl: "https://pancakeswap.finance/liquidity",
  },
  {
    id: "pancake-susdat",
    name: "PancakeSwap LP — USDT/sUSDat",
    protocol: "PancakeSwap",
    asset: "sUSDat",
    pairAsset: "USDT",
    yieldType: "Variable",
    apy: 0,
    apyMin: 0,
    apyMax: 0,
    riskLevel: "Medium",
    tvl: 4_100_000,
    chain: "BNB Chain",
    description:
      "Provide USDT/sUSDat liquidity on PancakeSwap to earn trading fees plus CAKE incentives.",
    longDescription:
      "Bridges sUSDat to BNB Chain liquidity via a USDT/sUSDat pool on PancakeSwap. Because sUSDat's price appreciates as STRC dividends accrue, this pool sees higher fee income than the USDat pair, layered with CAKE liquidity-mining incentives.",
    riskExplanation:
      "Medium risk. sUSDat's appreciating price versus flat USDT creates directional exposure and impermanent-loss dynamics beyond a stable-stable pool, plus bridge risk from moving sUSDat to BNB Chain.",
    requirements: [
      "No minimum lock-up — withdraw liquidity at any time",
      "Deposit USDT and sUSDat in the pool's ratio on BNB Chain",
      "Any BNB Chain wallet",
    ],
    howToParticipate: [
      "Bridge sUSDat to BNB Chain and acquire USDT",
      "Deposit both into the PancakeSwap USDT/sUSDat pool",
      "Stake the LP token in PancakeSwap's farm for CAKE incentives",
      "Withdraw liquidity anytime to reclaim both assets plus fees",
    ],
    historicalYield: [
      { month: "Feb", apy: 5.8 },
      { month: "Mar", apy: 7.2 },
      { month: "Apr", apy: 8.1 },
      { month: "May", apy: 6.5 },
      { month: "Jun", apy: 6.2 },
      { month: "Jul", apy: 7.0 },
    ],
    externalUrl: "https://pancakeswap.finance/liquidity",
  },

  // ---- Morpho (looping + lending) ----
  {
    id: "looping-pt-usdat",
    name: "Looped PT-USDat",
    protocol: "Morpho",
    morphoStrategy: "Looping",
    asset: "USDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 15.0,
    apyMin: 0.0,
    apyMax: 35.0,
    riskLevel: "Medium",
    leverage: 10,
    tvl: 6_100_000,
    chain: "Ethereum",
    description:
      "Recursively loop PT-USDat against USDC on the same Morpho market used for PT-USDat/USDC lending, to roughly 10x leveraged exposure.",
    longDescription:
      "This strategy deposits PT-USDat as collateral on Morpho's PT-USDat/USDC market, borrows USDC against it, buys more PT-USDat with the borrowed USDC, and redeposits — repeating to reach roughly 10x leveraged exposure, held below the market's 91.5% LLTV (which theoretically caps leverage at ~11.8x) for a safety buffer. Because the borrow cost is a separate variable rate, the net yield is leveraged PT-USDat fixed yield minus leveraged USDC borrow cost, both from the exact market listed under Lending.",
    riskExplanation:
      "Medium risk. USDat is backed by short-duration T-bills, so its value is stable and doesn't swing the way an equity-backed asset would — even at 10x leverage, the dominant risk is a widening spread if USDC borrow rates rise, not a sudden collateral-price crash. PT-USDat also converges predictably to face value, which keeps liquidation risk from price divergence comparatively low.",
    requirements: [
      "No official minimum — size the position so looping gas costs are worthwhile",
      "Comfortable actively monitoring borrow rates and LTV",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire PT-USDat on Pendle",
      "Deposit PT-USDat as collateral on the Morpho PT-USDat/USDC market",
      "Borrow USDC against the collateral at a target LTV",
      "Swap borrowed USDC for more PT-USDat and redeposit; repeat to reach target leverage",
    ],
    historicalYield: [
      { month: "Feb", apy: 14.8 },
      { month: "Mar", apy: 21.4 },
      { month: "Apr", apy: 25.6 },
      { month: "May", apy: 16.2 },
      { month: "Jun", apy: 15.4 },
      { month: "Jul", apy: 19.0 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "looping-pt-susdat",
    name: "Looped PT-sUSDat",
    protocol: "Morpho",
    morphoStrategy: "Looping",
    asset: "sUSDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 26.7,
    apyMin: 17.0,
    apyMax: 38.0,
    riskLevel: "High",
    leverage: 3,
    tvl: 5_400_000,
    chain: "Ethereum",
    description:
      "Recursively loop PT-sUSDat against USDC on the same Morpho market used for PT-sUSDat/USDC lending, to lever up its fixed rate.",
    longDescription:
      "The same recursive looping mechanic as Looped PT-USDat, but applied to PT-sUSDat — Pendle's fixed-rate wrapper on Saturn's STRC-backed yield token. Because PT-sUSDat's fixed rate is higher than PT-USDat's, looping it produces a higher net leveraged yield, using the exact Morpho market listed under Lending.",
    riskExplanation:
      "High risk. sUSDat's value tracks STRC — Strategy's (formerly MicroStrategy) preferred equity, not a stable T-bill-like asset — so 3x leverage compounds real collateral-value risk on top of borrow-rate risk. A rise in USDC borrow rates or a drop in STRC's value can trigger liquidation faster than an unlevered position.",
    requirements: [
      "No official minimum — size the position so looping gas costs are worthwhile",
      "Comfortable actively monitoring borrow rates and LTV",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire PT-sUSDat on Pendle",
      "Deposit PT-sUSDat as collateral on the Morpho PT-sUSDat/USDC market",
      "Borrow USDC against the collateral at a target LTV",
      "Swap borrowed USDC for more PT-sUSDat and redeposit; repeat to reach target leverage",
    ],
    historicalYield: [
      { month: "Feb", apy: 20.6 },
      { month: "Mar", apy: 30.2 },
      { month: "Apr", apy: 36.8 },
      { month: "May", apy: 23.4 },
      { month: "Jun", apy: 21.8 },
      { month: "Jul", apy: 27.0 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "looping-pt-srusdat",
    name: "Looped PT-srUSDat",
    protocol: "Morpho",
    morphoStrategy: "Looping",
    asset: "srUSDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 25.0,
    apyMin: 12.0,
    apyMax: 38.0,
    riskLevel: "Medium",
    leverage: 5,
    tvl: 3_800_000,
    chain: "Ethereum",
    description:
      "Recursively loop PT-srUSDat against USDC on the same Morpho market used for PT-srUSDat/USDC lending, to roughly 5x leveraged exposure.",
    longDescription:
      "The same recursive looping mechanic as Looped PT-USDat, but applied to PT-srUSDat — Pendle's fixed-rate wrapper on Saturn's senior Strata tranche. srUSDat's junior-tranche first-loss protection carries through to the PT, so this loop targets a higher leverage (5x vs. 3x) than the other loops with comparatively lower principal risk than looping PT-sUSDat.",
    riskExplanation:
      "Medium risk. srUSDat is protected by jrUSDat's first-loss position, so it takes a severe STRC drawdown before any loss reaches the senior tranche — meaningfully steadier than looping PT-sUSDat's unprotected exposure. 5x leverage still means a large enough STRC drawdown to exhaust the junior buffer would move through to PT-srUSDat's price and trigger liquidation.",
    requirements: [
      "No official minimum — size the position so looping gas costs are worthwhile",
      "Comfortable actively monitoring borrow rates and LTV",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire PT-srUSDat on Pendle",
      "Deposit PT-srUSDat as collateral on the Morpho PT-srUSDat/USDC market",
      "Borrow USDC against the collateral at a target LTV",
      "Swap borrowed USDC for more PT-srUSDat and redeposit; repeat to reach target leverage",
    ],
    historicalYield: [
      { month: "Feb", apy: 19.8 },
      { month: "Mar", apy: 28.6 },
      { month: "Apr", apy: 34.9 },
      { month: "May", apy: 22.4 },
      { month: "Jun", apy: 20.9 },
      { month: "Jul", apy: 26.0 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "looping-susdat",
    name: "Looped sUSDat",
    protocol: "Morpho",
    morphoStrategy: "Looping",
    asset: "sUSDat",
    pairAsset: "AUSD",
    yieldType: "Variable",
    apy: 13.4,
    apyMin: 8.0,
    apyMax: 22.0,
    riskLevel: "High",
    leverage: 3,
    tvl: 3_000_000,
    chain: "Ethereum",
    description:
      "Recursively loop sUSDat against AUSD on the same Morpho market used for sUSDat/AUSD lending, to lever up sUSDat's Hold APR.",
    longDescription:
      "This strategy deposits sUSDat as collateral on Morpho's sUSDat/AUSD market, borrows AUSD against it, swaps the AUSD for more sUSDat, and redeposits — repeating to reach roughly 3x leveraged exposure to sUSDat's Hold APR. Unlike the PT loops, collateral is live (appreciating) sUSDat rather than a fixed-maturity PT, so the leveraged leg tracks sUSDat's share price directly rather than converging to a discount at maturity.",
    riskExplanation:
      "High risk. sUSDat's value tracks STRC — Strategy's (formerly MicroStrategy) preferred equity — which behaves like a volatile, BTC-linked security rather than a stable asset. With no tranche protection and 3x leverage, a drop in STRC's value flows directly into sUSDat's price and can trigger liquidation.",
    requirements: [
      "No official minimum — size the position so looping gas costs are worthwhile",
      "Comfortable actively monitoring borrow rates and LTV",
      "Any Ethereum wallet",
    ],
    howToParticipate: [
      "Acquire sUSDat by staking USDat",
      "Deposit sUSDat as collateral on the Morpho sUSDat/AUSD market",
      "Borrow AUSD against the collateral at a target LTV",
      "Swap borrowed AUSD for more sUSDat and redeposit; repeat to reach target leverage",
    ],
    historicalYield: [
      { month: "Feb", apy: 10.6 },
      { month: "Mar", apy: 15.8 },
      { month: "Apr", apy: 19.4 },
      { month: "May", apy: 12.8 },
      { month: "Jun", apy: 11.6 },
      { month: "Jul", apy: 13.4 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "morpho-saturn-usdc",
    name: "Saturn USDC Vault",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "USDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 8.5,
    apyMin: 6.0,
    apyMax: 11.0,
    riskLevel: "Low",
    tvl: 31_000_000,
    chain: "Ethereum",
    description:
      "Supply USDC to Saturn's own curated Morpho vault, which allocates across the PT-USDat, PT-sUSDat, and PT-srUSDat collateral markets.",
    longDescription:
      "The Saturn USDC vault is Saturn's flagship curated lending vault on Morpho: depositors supply USDC once, and the vault's curator allocates it across Saturn's isolated PT-collateral markets (PT-USDat, PT-sUSDat, PT-srUSDat) rather than requiring suppliers to pick a single market themselves. Interest is paid by borrowers across those markets and passed through to vault suppliers.",
    riskExplanation:
      "Low risk. The vault only allocates to Saturn's own overcollateralized PT-collateral markets, and Morpho's isolated-market design limits contagion between them. Primary risks are curator allocation decisions, oracle risk, and collateral liquidity in a fast market move.",
    requirements: [
      "No minimum lock-up — withdraw supplied USDC anytime liquidity allows",
      "Any Ethereum wallet",
      "View live vault APY and TVL on Morpho",
    ],
    howToParticipate: [
      "Acquire USDC",
      "Open the Saturn USDC vault on Morpho",
      "Supply USDC to start earning the vault's variable rate",
      "Withdraw anytime, subject to available vault liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 6.4 },
      { month: "Mar", apy: 7.6 },
      { month: "Apr", apy: 9.8 },
      { month: "May", apy: 10.2 },
      { month: "Jun", apy: 7.9 },
      { month: "Jul", apy: 8.5 },
    ],
    externalUrl: SATURN_USDC_VAULT_URL,
  },
  {
    id: "morpho-pt-usdat-usdc",
    name: "PT-USDat / USDC",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "USDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 7.67,
    apyMin: 5.5,
    apyMax: 9.5,
    riskLevel: "Low",
    tvl: 59_840_000,
    chain: "Ethereum",
    description:
      "Supply USDC to Saturn's Hyperithm-curated Morpho market that lends against PT-USDat collateral.",
    longDescription:
      "This isolated Morpho market, curated by Hyperithm, lets borrowers post PT-USDat (Pendle's fixed-rate USDat token) as collateral to borrow USDC, accessing liquidity without giving up their locked fixed-rate position before maturity. USDC suppliers earn the interest borrowers pay.",
    riskExplanation:
      "Low risk. USDat is backed by short-duration T-bills, so its value is stable and PT-USDat converges predictably to face value at maturity — collateral is unlikely to move sharply enough to threaten supplier funds. Residual risk is limited to standard Morpho isolated-market and oracle risk.",
    requirements: [
      "No minimum lock-up — withdraw supplied USDC anytime liquidity allows",
      "Any Ethereum wallet",
      "View live market APY and utilization on Morpho",
    ],
    howToParticipate: [
      "Acquire USDC",
      "Open the PT-USDat/USDC market on Morpho",
      "Supply USDC to start earning the market's variable rate",
      "Withdraw anytime, subject to available market liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 6.8 },
      { month: "Mar", apy: 7.9 },
      { month: "Apr", apy: 10.2 },
      { month: "May", apy: 10.6 },
      { month: "Jun", apy: 8.4 },
      { month: "Jul", apy: 8.91 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "morpho-pt-susdat-usdc",
    name: "PT-sUSDat / USDC",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "sUSDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 12.23,
    apyMin: 9.0,
    apyMax: 15.0,
    riskLevel: "Medium",
    tvl: 20_110_000,
    chain: "Ethereum",
    description:
      "Supply USDC to Saturn's Hyperithm-curated Morpho market that lends against PT-sUSDat collateral.",
    longDescription:
      "Borrowers post PT-sUSDat (Pendle's fixed-rate sUSDat token) as collateral to borrow USDC, unlocking liquidity while keeping their locked-in fixed rate on sUSDat intact until maturity. USDC suppliers earn the interest borrowers pay.",
    riskExplanation:
      "Medium risk. Collateral value depends on PT-sUSDat pricing and, indirectly, sUSDat's underlying STRC performance — adding oracle and liquidation-timing risk on top of standard Morpho isolated-market risk.",
    requirements: [
      "No minimum lock-up — withdraw supplied USDC anytime liquidity allows",
      "Any Ethereum wallet",
      "View live market APY and utilization on Morpho",
    ],
    howToParticipate: [
      "Acquire USDC",
      "Open the PT-sUSDat/USDC market on Morpho",
      "Supply USDC to start earning the market's variable rate",
      "Withdraw anytime, subject to available market liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 10.2 },
      { month: "Mar", apy: 11.6 },
      { month: "Apr", apy: 14.8 },
      { month: "May", apy: 14.2 },
      { month: "Jun", apy: 11.8 },
      { month: "Jul", apy: 12.41 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "morpho-pt-srusdat-usdc",
    name: "PT-srUSDat / USDC",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "srUSDat",
    pairAsset: "USDC",
    yieldType: "Variable",
    apy: 11.32,
    apyMin: 8.0,
    apyMax: 13.5,
    riskLevel: "Low",
    tvl: 5_120_000,
    chain: "Ethereum",
    description:
      "Supply USDC to Saturn's Hyperithm-curated Morpho market that lends against PT-srUSDat collateral.",
    longDescription:
      "Borrowers post PT-srUSDat (Pendle's fixed-rate senior Strata tranche token) as collateral to borrow USDC. Because srUSDat is Saturn's more stable senior tranche, this market's collateral is comparatively steadier than the PT-sUSDat market, even with the added PT pricing dynamic.",
    riskExplanation:
      "Low risk. srUSDat is protected by jrUSDat's first-loss position, so it takes a severe STRC drawdown before any loss reaches the senior tranche — and PT-srUSDat converges predictably to face value at maturity on top of that. Residual risk is limited to standard Morpho isolated-market and oracle risk.",
    requirements: [
      "No minimum lock-up — withdraw supplied USDC anytime liquidity allows",
      "Any Ethereum wallet",
      "View live market APY and utilization on Morpho",
    ],
    howToParticipate: [
      "Acquire USDC",
      "Open the PT-srUSDat/USDC market on Morpho",
      "Supply USDC to start earning the market's variable rate",
      "Withdraw anytime, subject to available market liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 9.8 },
      { month: "Mar", apy: 10.6 },
      { month: "Apr", apy: 12.9 },
      { month: "May", apy: 13.2 },
      { month: "Jun", apy: 11.0 },
      { month: "Jul", apy: 11.59 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "morpho-pt-usdat-ausd",
    name: "PT-USDat / AUSD",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "USDat",
    pairAsset: "AUSD",
    yieldType: "Variable",
    apy: 6.8,
    apyMin: 4.5,
    apyMax: 9.0,
    riskLevel: "Low",
    tvl: 1_800_000,
    chain: "Ethereum",
    description:
      "Supply AUSD to an isolated Morpho market that lends against PT-USDat collateral.",
    longDescription:
      "The same PT-USDat collateral market as PT-USDat/USDC, but with AUSD as the loan asset instead of USDC — useful for AUSD holders who want exposure to Saturn's PT-USDat borrow demand without first converting to USDC.",
    riskExplanation:
      "Low risk. USDat is backed by short-duration T-bills, so PT-USDat collateral is unlikely to move sharply, and it converges predictably to face value at maturity. The main residual risk is AUSD's own reserve and redemption risk as the loan asset, not the collateral.",
    requirements: [
      "No minimum lock-up — withdraw supplied AUSD anytime liquidity allows",
      "Any Ethereum wallet",
      "View live market APY and utilization on Morpho",
    ],
    howToParticipate: [
      "Acquire AUSD",
      "Open the PT-USDat/AUSD market on Morpho",
      "Supply AUSD to start earning the market's variable rate",
      "Withdraw anytime, subject to available market liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 5.2 },
      { month: "Mar", apy: 6.0 },
      { month: "Apr", apy: 8.4 },
      { month: "May", apy: 8.8 },
      { month: "Jun", apy: 6.4 },
      { month: "Jul", apy: 6.8 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
  {
    id: "morpho-susdat-ausd",
    name: "sUSDat / AUSD",
    protocol: "Morpho",
    morphoStrategy: "Lending",
    asset: "sUSDat",
    pairAsset: "AUSD",
    yieldType: "Variable",
    apy: 10.2,
    apyMin: 7.0,
    apyMax: 14.0,
    riskLevel: "Medium",
    tvl: 4_600_000,
    chain: "Ethereum",
    description:
      "Supply AUSD to an isolated Morpho market that lends directly against sUSDat collateral.",
    longDescription:
      "Unlike the PT-collateral markets, this market takes plain sUSDat as collateral directly — no Pendle wrapper. Borrowers post sUSDat to borrow AUSD, and suppliers earn the resulting interest. Because collateral is live (appreciating) sUSDat rather than a fixed-maturity PT, pricing tracks sUSDat's share price in real time.",
    riskExplanation:
      "Medium risk. Collateral value tracks sUSDat's share price directly, which is tied to STRC's performance as Strategy's preferred equity. Suppliers also take on AUSD's own reserve and redemption risk as the loan asset.",
    requirements: [
      "No minimum lock-up — withdraw supplied AUSD anytime liquidity allows",
      "Any Ethereum wallet",
      "View live market APY and utilization on Morpho",
    ],
    howToParticipate: [
      "Acquire AUSD",
      "Open the sUSDat/AUSD market on Morpho",
      "Supply AUSD to start earning the market's variable rate",
      "Withdraw anytime, subject to available market liquidity",
    ],
    historicalYield: [
      { month: "Feb", apy: 8.4 },
      { month: "Mar", apy: 9.6 },
      { month: "Apr", apy: 13.1 },
      { month: "May", apy: 12.0 },
      { month: "Jun", apy: 9.4 },
      { month: "Jul", apy: 10.2 },
    ],
    externalUrl: "https://app.morpho.org/ethereum",
  },
];

export function getOpportunityById(id: string): Opportunity | undefined {
  return opportunities.find((o) => o.id === id);
}
